### ISSUE TITLE
Bug: [Linux native & Flatpak] Selected entries displayed white

### ISSUE THREAD

**Issue by ozolli** [rgleason/weatherfax_pi#107]
In the "Weather Fax" window, "Fax" menu list and in the "Internet Retrieval" window, "Servers" and "Regions" menu lists, the selected entries are displayed in white. In the Flatpak version they are still readable as "embossed" black, but they are invisible in linux native.

See this capture on Ubuntu: 
![WeatherFax_selected_bug](https://user-images.githubusercontent.com/1449802/169790958-74e00ddf-5963-460a-bc4a-ae76d2ea75b3.png)

**Comment by ozolli** [comment]
Flatpak capture: 
![WeatherFax_flatpak_selected](https://user-images.githubusercontent.com/1449802/169791585-03700f75-b546-451a-b064-7b1d3b950dd3.png)

**Comment by rgleason** [comment]
Thank you for the screenshots, this should help with understanding. We had an earlier report about this. 
I wonder if it is due to something missing in the xml?  or is it related to the OS and wx plugin programming used?

**Comment by rgleason** [comment]
Is this still a problem in  Linux Native and Flatpak??

This is a Windows screen grab of the list.

![Screenshot (1745)](https://github.com/rgleason/weatherfax_pi/assets/2363959/b335dcf6-d4f8-4770-a72f-3deb9d3f61f7)

**Comment by ozolli** [comment]
Hi Rick,

I don't use native linux anymore so I can't tell you.
Flatpak is ok.

Olivier Zolli


Le mar. 5 sept. 2023 à 03:22, Rick Gleason ***@***.***> a
écrit :

**Comment by rgleason** [comment]
Thanks, then I think we can close this now, as no other reports. We can reopen if necessary.
