### ISSUE TITLE
Retrieve > Update Data Sources  - Improvements

### ISSUE THREAD

**Issue by rgleason** [rgleason/weatherfax_pi#115]
In weatherfax.cpp at LINE 828

```
void WeatherFax::OnUpdateData( wxCommandEvent& event )
{
    if( DownloadFile( _T("WeatherFaxInternetRetrieval_NOAA.xml") ) &&
      DownloadFile( _T("WeatherFaxInternetRetrieval_NOAA_OPC.xml") ) &&
      DownloadFile( _T("WeatherFaxInternetRetrieval_NAVY.xml") ) &&
      DownloadFile( _T("WeatherFaxInternetRetrieval_PWx_Amer_Atl.xml") ) &&
      DownloadFile( _T("WeatherFaxInternetRetrieval_Aviation_Weather.xml") ) &&
      DownloadFile( _T("WeatherFaxInternetRetrieval_PWx_Euro_Atl.xml") ) &&
      DownloadFile( _T("WeatherFaxInternetRetrieval_LaMMA.xml") ) &&
      DownloadFile( _T("WeatherFaxInternetRetrieval_Europe.xml") ) &&
      DownloadFile( _T("WeatherFaxInternetRetrieval_PWx_India.xml") ) &&
      DownloadFile( _T("WeatherFaxInternetRetrieval_Australia.xml") ) &&
      DownloadFile( _T("WeatherFaxInternetRetrieval_PWx_Pacific.xml") ) &&
      DownloadFile( _T("WeatherFaxInternetRetrieval_Misc.xml") ) &&
      DownloadFile( _T("CoordinateSets.xml") ) ) {
        m_InternetRetrievalDialog.Load(true);
    }
    if( DownloadFile( _T("WeatherFaxSchedules.xml") ) ) {
        m_SchedulesDialog.Load(true);
    }
}
```
As these are downloaded we would like a confirmation message:

```
"WeatherFaxInternetRetrieval_NOAA.xml"   - Success
"WeatherFaxInternetRetrieval_NOAA_OPC.xml" -Success
"WeatherFaxInternetRetrieval_NAVY.xml" - Success
"WeatherFaxInternetRetrieval_PWx_Amer_Atl.xml" - Fail
"WeatherFaxInternetRetrieval_Aviation_Weather.xml" - Success
"WeatherFaxInternetRetrieval_PWx_Euro_Atl.xml" - and so on.
"WeatherFaxInternetRetrieval_LaMMA.xml"
"WeatherFaxInternetRetrieval_Europe.xml"
"WeatherFaxInternetRetrieval_PWx_India.xml
"WeatherFaxInternetRetrieval_Australia.xml"
 "WeatherFaxInternetRetrieval_PWx_Pacific.xml"
"WeatherFaxInternetRetrieval_Misc.xml" - Success
 "CoordinateSets.xml" - Success
 "WeatherFaxSchedules.xml" - Success
Prompt: `Update/Overwrite the User (writable) CoordinatedSets.xml? Any user created Image Wizard custom coordinates will be lost.  Yes? No?
"User (writable) CoordinateSets.xml" - Success or Fail after the question.
```

Additionally we would like the User (writable)  CoordinateSets.xml file to be updated after this prompt is answered by the user.
`Update/Overwrite User (writable) CoordinatedSets.xml? User saved custom coordinates with Image Wizard will be lost.  Yes? No?
`
The User (writable) CoordinateSets prompt should also occur when the plugin is Installed or Updated.
See #89

**Comment by rgleason** [comment]
or maybe a better prompt:

WeatherfaxInternetRetrieval files have been updated and URL's updated, we now need to remove the User (writable) CoordinateSets.xml (which may contain user customizations), so that the new file will work properly.  Yes? No?

**Comment by ozolli** [comment]
Maybe move user's CoordinateSets.xml to CoordinateSets.xml.save and tell him he can merge his cutomizations if needed.

**Comment by rgleason** [comment]
Yes, that's a good answer.

"Update Data Sources"  should:

1. Download and over write the xml data files in the Installation Directory (refer to the [Development Manual Installation Paths](https://opencpn-manuals.github.io/main/plugin-installer/Installation-paths.html) :
- WeatherfaxInternetRetrieval_(regions).xml 
- WeatherfaxSchedules.xml
- CoordinateSets.xml

2. Rename the 

- Windows 10  - User Writable and Actively Used Data Location: C:\ProgramData\opencpn\plugins\weatherfax\coordinateSets.xml
- Ubuntu      User Writable and Actively Used Data Location: $HOME/.var/app/org.opencpn.OpenCPN/config/opencpn/plugins/coordinateSets.xml

To coordinateSets.save.xml  (also rename user_coordinates.xml if it exists, to user_coordinates.save.xml)

**Comment by rgleason** [comment]
OK, Ozolli. thanks. Changed to Flatpak in the post above.

**Comment by rgleason** [comment]
Dave's PR for fixing this.
https://github.com/rgleason/weatherfax_pi/commit/ee64697df1d99ce0ff2f41232982ddac73477629
