### ISSUE TITLE
New South Atlantic chart from Marinha Do Brasil

### ISSUE THREAD

**Issue by ozolli** [rgleason/weatherfax_pi#133]
Hi Rick,

Found a much better one that the chart from Chile Met:
![Capture d’écran du 2022-11-19 17-01-19](https://user-images.githubusercontent.com/1449802/202860049-2417e2f7-af86-415c-b49c-3f864666a396.png)

Here are the files:
[WFIR_Misc.zip](https://github.com/rgleason/weatherfax_pi/files/10047416/WFIR_Misc.zip)

Cheers,
Olivier.

**Comment by ozolli** [comment]
Just found a wrong mapping on Aviation Weather - Sat Images Water-Vapor - Atlantic.
Corrected CoordinateSets files attached :
[CoordinateSets.zip](https://github.com/rgleason/weatherfax_pi/files/10179155/CoordinateSets.zip)

**Comment by rgleason** [comment]
Oliver, thank you. I will be updating PI for 5.8.1 shortly and will make these changes then.

**Comment by rgleason** [comment]
Olivier,  It's wonderful you found a good Surface chart for South America,
I am applying these now.  First the surface chart files, then the coord files. 
Wxfax is also updated for 5.7.1   Will push these shortly.  Thanks.
