### ISSUE TITLE
Build Failure: MacOS and MacOS-wx32  

### ISSUE THREAD

**Issue by rgleason** [rgleason/weatherfax_pi#143]
Pouring gettext--0.21.1.big_sur.bottle.tar.gz Error: No such file or directory @ rb_sysopen - /Us 
https://app.circleci.com/pipelines/github/rgleason/weatherfax_pi/364/workflows/3f353fbf-4f2d-4c0a-8d4a-26b226b8db66/jobs/5092
https://app.circleci.com/pipelines/github/rgleason/weatherfax_pi/364/workflows/3f353fbf-4f2d-4c0a-8d4a-26b226b8db66/jobs/5108

Circleci Support Request
https://support.circleci.com/hc/en-us/requests/138832

**Comment by bdbcat** [comment]
Close now?
