### ISSUE TITLE
Bug: Flatpak Receiving sound

### ISSUE THREAD

**Issue by rgleason** [rgleason/weatherfax_pi#159]
https://github.com/OpenCPN/OpenCPN/issues/3216
Flatpak requires that its own package for receiving sound is used.

**Comment by rgleason** [comment]
@filochard  Is this fixed now that we updated libaudiofile?

**Comment by rgleason** [comment]
Closing, covered as part of another Issue.

**Comment by filochard** [comment]
> @filochard Is this fixed now that we updated libaudiofile?

Hi Rick
I can't test flatpak at home (no radio receiver connected to my computer)
I can only say that with our weatherfax_pi rpm built upon  our own patched libaudiofile (instead of the bundled one) weatherfax works perfectly
There's no reason it would be different for flatpak

**Comment by rgleason** [comment]
Good!  Thanks.  Help me understand this a little. These libaudio files are used by only Linux and flatpak Weatherfax?

**Comment by filochard** [comment]
I don't know if it is necessary for Windows MacOS or androïd 

What I know is that this src/libaudiofile can be used by FaxDecoder.cpp and FaxDecoder.h 
FaxDecoder can then transform an audio signal into characters to write a fax that can then be displayed by weatherfax_pi

about libaudiofile itself it's a libray written in C  https://audiofile.68k.org/  and might be used by any OS to compile the plugin
NB this library is 8 years old and no more maintained but still useful :  that's the reason why patches have been added by linux distributions 

Maybe you should ask Sean Depagnier
