### ISSUE TITLE
XML: no more faxes from French Polynesia

### ISSUE THREAD

**Issue by filochard** [rgleason/weatherfax_pi#167]
Hi Rick

Since I could not download anymore faxes from French Polynesia server, (https://meteo.pf ) I wrote to them to know if their address had been changed...
Indeed they answered me they don't provide anymore images on their site :-(    there are only text files
(French Meteo Services are decreasing the number of employees and there no one to create images now !)

You may remove some lines inside /data/WeatherFaxInternetRetrieval_Misc.xml
lines 14 to 30 are useless now

And the lines about French Polynesia inside : 
Coordinates-Sets-high.xml
Coordinates-Sets-normal.xml
Coordinates-Sets.xml

**Comment by rgleason** [comment]
Done,  and pushed
```
You may remove some lines inside /data/WeatherFaxInternetRetrieval_Misc.xml
lines 14 to 30 are useless now

And the lines about French Polynesia inside :
Coordinates-Sets-high.xml
Coordinates-Sets-normal.xml
Coordinates-Sets.xml
```
