### ISSUE TITLE
BUG Weatherfax plugin will not install or boot since recent updates to Open CPN

### ISSUE THREAD

**Issue by Devman25** [rgleason/weatherfax_pi#168]
Recently had it where OpenCPN updated enough that my plugins had disappeared. This was with OpenCPN 5.8.2. Upon reinstalling my plugins - only my WeatherFax plugin had an issue - and said "an error occurred during installation and the plugin will be uninstalled". Every time I open OpenCPN I also get an error saying "The following plugin has encountered an error during startup (WeatherFax) - It will be uninstalled". I've since tried updating OpenCPN further to the latest (OpenCPN 5.10.2) and my operating system (MacOS 15.0) and the problem still exists.

Please let me know of any solutions to this issue - really hoping to be able to use this plugin ASAP.

Thanks!

**Comment by rgleason** [comment]
Have updated Logbook's shipdriver template to SD3.3.0 and the metadata and tar are on cloudsmith here  https://cloudsmith.io/~opencpn/repos/logbookkonni-prod/packages/
You can find your OS and download and install, or wait until I push it to the plugins repos.

**Comment by Devman25** [comment]
Hi Rick - are you aware of a way to solve the install issue with the Weatherfax plugin?

**Comment by rgleason** [comment]
I need to update the frontend first, will do this in several days.

**Comment by Devman25** [comment]
Hi Rick,

Thanks for getting back to me and working on it. Hopeful to have it working ASAP as I’m heading offshore shortly and would like to use it for receiving weather forecasts while offshore.

Keep me posted.

Cheers,

-Devin

Devin Jones
***@***.***

On Sep 29, 2024, at 18:33, Rick Gleason ***@***.***> wrote:



I need to update the frontend first, will do this in several days.

**Comment by rgleason** [comment]
Have you updated the PLugin Catalog!  
That is a very important first step.

**Comment by Devman25** [comment]
Hi Rick,

Thanks for getting back to me.

I have updated the plugin catalog and just updated it again now and tried again. The Weatherfax plugin still will not install properly.

Please let me know what next steps you’d advise.

Thanks,

-Devin

Devin Jones
613-371-6751
***@***.***

On Oct 2, 2024, at 19:09, Rick Gleason ***@***.***> wrote:



Have you updated the PLugin Catalog!
That is a very important first step.

**Comment by rgleason** [comment]
Weatherfax is working for me on Windows 11.  Do you know how to use it?
Will you please do a search on weatherfax_pi and advise what directories it is found in?

I think your older version may have been installed in a different directory, and you are updating from a very much older version.
You will want to first remove weatherfax plugin from the Options > Plugin page. Close Opencpn
Then do a search on weatherfax  and weatherfax_pi  find the instances of this and remove them.
Then go back to OpenCPN and update the catalog and install the plugin.
Hopefully it will work.

**Comment by Devman25** [comment]
Hi Rick,

Thanks for getting back to me.

I’m familiar with how to use the Weatherfax plugin as I used it regularly until it disappeared from my toolbar following a recent update of OpenCPN to 5.10.2. All other plugins have reinstalled and work without issue.

I’m on MacOS Secquoia 15.0.

Tried searching “weatherfax_pi” and my computer didn’t turn up anything. Same goes for “weatherfax”. On the options->plugin page it shows as if it’s unintalled.

Please let me know how to proceed. I’ve attached a screenshot of the error I get each time I open OpenCPN.

Thanks,

-Devin

Devin Jones
613-371-6751
***@***.***

[Screenshot 2024-10-21 at 13.06.48.png]

On Oct 6, 2024, at 18:27, Rick Gleason ***@***.***> wrote:



Weatherfax is working for me on Windows 11. Do you know how to use it?
Will you please do a search on weatherfax_pi and advise what directories it is found in?

I think your older version may have been installed in a different directory, and you are updating from a very much older version.
You will want to first remove weatherfax plugin from the Options > Plugin page. Close Opencpn
Then do a search on weatherfax and weatherfax_pi find the instances of this and remove them.
Then go back to OpenCPN and update the catalog and install the plugin.
Hopefully it will work.

**Comment by rgleason** [comment]
You are using MacOS Secquoia 15.0.  and   OpenCPN to 5.10.2.  
You cannot find Weatherfax 1.9.20.
Have you updated your plugin catalog and installed weatherfax? 
Please refer to the manual for installation of plugins.

**Comment by Devman25** [comment]
Hi Rick,

I can find Weatherfax 1.9.20 in the plugin installer - but regardless whether I click the 1.9.111.1 or 1.9.20.0 - neither successfully installs and I get the error that I already sent you whenever I startup OpenCPN. I’ve also tried uninstalling and reinstalling OpenCPN.

Please let me know what to try next.

Thanks,

-Devin

Devin Jones
***@***.***

[Screenshot 2024-10-21 at 17.37.56.png]

On Oct 21, 2024, at 16:08, Rick Gleason ***@***.***> wrote:



You are using MacOS Secquoia 15.0. and OpenCPN to 5.10.2.
You cannot find Weatherfax 1.9.20.
Have you updated your plugin catalog and installed weatherfax?
Please refer to the manual for installation of plugins.

**Comment by rgleason** [comment]
Thank you for your report. Devman25 for your report and effort. We'll try to get this fixed.

**Comment by Devman25** [comment]
Thanks a ton.

Will stay tuned!

-Devin

Devin Jones
***@***.***

On Oct 21, 2024, at 18:45, Rick Gleason ***@***.***> wrote:



Thank you for your report. Devman25 for your report and effort. We'll try to get this fixed.

**Comment by Devman25** [comment]
Hi Rick,

Hope you’ve had a great week.

Was wondering if there has been any progress in fixing the Weatherfax plugin? I’m still having the same issue.

Thanks!

-Devin

Devin Jones
***@***.***

On Oct 21, 2024, at 18:45, Rick Gleason ***@***.***> wrote:



Thank you for your report. Devman25 for your report and effort. We'll try to get this fixed.

**Comment by rgleason** [comment]
@Devman25   We are having some difficulties getting bugs resolved, but I hope this will install on you Mac. Can you please pick the right tarball version and download it and use Import Plugin Tarball to install.  Let me know here please.
https://cloudsmith.io/~opencpn/repos/weatherfax-prod/packages/?q=1.10.3+tarball+mac
Thanks.

**Comment by rgleason** [comment]
@Devman25 
Can you also advise regarding these other older MacOS bugs?  Are they fixed or a problem still?
https://github.com/rgleason/weatherfax_pi/issues/112   Can this be closed now?

**Comment by Devman25** [comment]
Sorry Rick. Haven’t had time to mess with it as I’m sailing down the coast to Mexico and don’t have starlink or time at the moment. Will reply as soon as I arrive and have a chance. REALLY appreciate your help and efforts!

-Devin

On Dec 20, 2024, at 08:44, Rick Gleason ***@***.***> wrote:

﻿

@Devman25<https://github.com/Devman25>
Can you also advise regarding these other older MacOS bugs? Are they fixed or a problem still?
#112<https://github.com/rgleason/weatherfax_pi/issues/112> Can this be closed now?

**Comment by rgleason** [comment]
Ok thanks.

**Comment by rgleason** [comment]
Devman, if you happen to get a chance, theres a new version here 
https://cloudsmith.io/~opencpn/repos/weatherfax-beta/packages/?q=1.10.4+darwin++tarball

Pick the most recent one that matches your MacOS please.

**Comment by rgleason** [comment]
Closing, if it does not work. Reopen or post new.

**Comment by Devman25** [comment]
Hi Rick,

Happy new year!

Wanted to report that I’ve finally had a chance to install the new update and it has infact solved the problems I was having.

Thanks a ton for all your help in troubleshooting this and following up!

Cheers,

-Devin

On Dec 22, 2024, at 19:27, Rick Gleason ***@***.***> wrote:



Closing, if it does not work. Reopen or post new.
