### ISSUE TITLE
Mapping Failed

### ISSUE THREAD

**Issue by ThomTrab** [rgleason/weatherfax_pi#50]
Hello,

I started using this plugin some months ago without issue.
Now when I try to download fax images from Internet from German Weather DWD or UK MET for example. I got the following error message.
![image](https://user-images.githubusercontent.com/9775724/115590547-5f8ef100-a2d1-11eb-9a82-144153137b33.png)

What can I do to solve this ? I already try to reinstall the plugin.

Thank you for your help

**Comment by rgleason** [comment]
Tom, the underlying website has changed so the data files need to be updated. Do you know what the new url is?  There is more info in the manual.

**Comment by ThomTrab** [comment]
Thanks for your answer. But I'm not sure to follow you.

After the above error message, I get the following window, that ask me to adapt the image to the map. This part was automatic, as far as I remember.
![image](https://user-images.githubusercontent.com/9775724/115603441-70932e80-a2e0-11eb-8e99-9a9107aeeecc.png)
That let me think that download is OK, isn't it ?

> There is more info in the manual.

Do you mean edit the `WeatherFaxInternetRetrieval.xml`file ?

**Comment by ThomTrab** [comment]
I don't know how but I had messed up with my `CoordinateSets.xml`.

Copying over the one from the git repo solved my issue. :+1:

I apologize for the disturbance.

**Comment by rgleason** [comment]
Dear Thom
You can learn how to use the Image Wizard to adjust any image to overlay properly onto Opencpn charts.
The manual should give you some ideas how to do that.
Those settings are then saved in coordinatedatasets.xml  and weatherfaxinternetretrieval.xml

We need people who are familiar with this process and can help update the files.

**Comment by rgleason** [comment]
Thank you ThomTrab.  That will be very helpful.  Between me, you and Hans who also is good at this, we should be able to get this done reasonably quickly. I will contact you and Hans with a workflow proposal to split up the areas.  I really like your PR, that is the best way to do this.
