### ISSUE TITLE
French Polynesia update - Completed v1.9.30.3

### ISSUE THREAD

**Issue by ozolli** [rgleason/weatherfax_pi#72]
Hello,

Here are the files with updated French Polynesia internet weather data.
Sorry but I haven't done a PR for ages ;-)
Cheers, Olivier.

[CoordinateSets.xml.gz](https://github.com/rgleason/weatherfax_pi/files/8556496/CoordinateSets.xml.gz)
[WeatherFaxInternetRetrieval_Misc.xml.gz](https://github.com/rgleason/weatherfax_pi/files/8556499/WeatherFaxInternetRetrieval_Misc.xml.gz)

**Comment by rgleason** [comment]
I've checked and added this. Will be part of the next release.

**Comment by rgleason** [comment]
ozolli, Is it working as you expect.?   and can we close this now?  Original Poster (OP) normally closes.

**Comment by ozolli** [comment]
Working fine! I will close it.
