### ISSUE TITLE
WFIR_LaMMA testing needed

### ISSUE THREAD

**Issue by rgleason** [rgleason/weatherfax_pi#83]
Low and High res appear to be working well.
I have a question about the hours.   We select a certain hour and the chart the comes up is one hour behind.
Is this due to daylight savings or something like that?  Or should we fix this?

**Comment by ozolli** [comment]
We can fix this, I just found out how: 
`   <Region Name="Ustica">`
`      <Iterator From="1" To="37" By="1" Offset="-1">`
`        <Map Url="wind10.X.%d.png" Contents="Wind %+dhr" Area="1" />`
`      </Iterator>`
You can see the Offset="-1" that was not present on line 257. This offset is taken in account with the %+d variable in the Contents section.

**Comment by rgleason** [comment]
Good. Thanks.

**Comment by ozolli** [comment]
Changes done. New file: 
[WeatherFaxInternetRetrieval_LaMMA.zip](https://github.com/rgleason/weatherfax_pi/files/8685583/WeatherFaxInternetRetrieval_LaMMA.zip)

**Comment by rgleason** [comment]
Have downloaded, extracted and overwritten the old version of  WFIR_LaMMA

**Comment by rgleason** [comment]
Thanks, have this in the data directory now. Closing
