### ISSUE TITLE
WFIR_ PW _   (America-Atlantic, Euro-Atlantic, Pacific)  - Testing needed

### ISSUE THREAD

**Issue by rgleason** [rgleason/weatherfax_pi#85]
I've done some preliminary testing of these and they appear to be OK

**Comment by ozolli** [comment]
All files tested and ok. I just needed to refine Med-Carib and Canary islands waves maps.

**Comment by rgleason** [comment]
Good.

**Comment by rgleason** [comment]
Ozolli, are there files for these or are they part of some files you uploaded with another xml set?

**Comment by rgleason** [comment]
> All files tested and ok. I just needed to refine Med-Carib and Canary islands waves maps.

I realize these changes are probably done in coordinatesets.xml

**Comment by rgleason** [comment]
Closing
