### ISSUE TITLE
WFIR_ (NOAA, NOAA_OPC, NAVY) testing

### ISSUE THREAD

**Issue by rgleason** [rgleason/weatherfax_pi#86]
These appear to be OK too, but others should test and report any issues here.

**Comment by ozolli** [comment]
There are new color versions of the charts. I'll have a look at it.
https://ocean.weather.gov/Atl_tab.php

**Comment by ozolli** [comment]
All tested and corrected. A lot of remapping involved ;-)
Updated files: 
[WeatherFaxInternetRetrieval_NOAA.zip](https://github.com/rgleason/weatherfax_pi/files/8688380/WeatherFaxInternetRetrieval_NOAA.zip)
[WeatherFaxInternetRetrieval_NOAA_OPC.zip](https://github.com/rgleason/weatherfax_pi/files/8688382/WeatherFaxInternetRetrieval_NOAA_OPC.zip)
[CoordinateSets.zip](https://github.com/rgleason/weatherfax_pi/files/8688389/CoordinateSets.zip)
(The CoordinateSets.xml is updated for all xml files).

**Comment by ozolli** [comment]
All tested and corrected. Involved a lot of remapping.
Here are the updated files: 
[WeatherFaxInternetRetrieval_NOAA.zip](https://github.com/rgleason/weatherfax_pi/files/8688954/WeatherFaxInternetRetrieval_NOAA.zip)
[WeatherFaxInternetRetrieval_NOAA_OPC.zip](https://github.com/rgleason/weatherfax_pi/files/8688957/WeatherFaxInternetRetrieval_NOAA_OPC.zip)
[CoordinateSets.zip](https://github.com/rgleason/weatherfax_pi/files/8688960/CoordinateSets.zip)
(The CoordinateSets.xml is updated for all the xml files I modified).

**Comment by rgleason** [comment]
Wow, ozolli. Super. Will pull your files together and jon has a new TP version.

**Comment by rgleason** [comment]
Ozolli,  I've downloaded, unzipped and overwrote these into weatherfax/data directory, including coordinateSets.xml
(I reviewed coodinateSets.xml first)

**Comment by rgleason** [comment]
Thanks have these in the data directory. Closing.
