### ISSUE TITLE
weatherfax_pi/data/WeatherFax-Update-Notes.md

### ISSUE THREAD

**Issue by ozolli** [rgleason/weatherfax_pi#90]
Basically everything in this file have been reviewed and corrected or discarded.: 

1. Mauricius: Discarded
2. Singapore: Discarded but awaiting for a reply from them hopefully
3. Japan: Discarded
4. South Africa: Updated
5. French Polynesia: Updated
6. Chile: Remapped (one Mercator changed to Fixed-Flat and one Conic to Polar)
7. PWx, GFS, ECMWF and UKMO for a better coverage
8. Europe: Updated

weatherfax_pi/data/MET-strdate-work-needed.md is obsolete too.

**Comment by rgleason** [comment]
@ozolli    Thank you. I've added your notes at the top to both docs. We may remove this later, but I want to make sure there are good examples available re strdate etc.  I will review and consolidate it.
